### PR TITLE
Implement script file including object control

### PR DESCRIPTION
**Pull request by Minghui-Gao**

### CODE REVIEW

**Comment by TejasJD** [comment]
Camera controls was not needed, in the source files, because eventually it is going to sit in the App assembly which would be in the project.

**Comment by TejasJD** [comment]
Getting game object by names is not a good function. Problem being, multiple game objects can easily have same names.

**Comment by Minghui-Gao** [comment]
> Getting game object by names is not a good function. Problem being, multiple game objects can easily have same names.

Yes. It makes sense. In the future we will have game objects with the same name

**Comment by TejasJD** [comment]
> > Getting game object by names is not a good function. Problem being, multiple game objects can easily have same names.
> 
> Yes. It makes sense. In the future we will have game objects with the same name

No, we have multiple game objects, with the same name in the engine right now.

**Review by LiamANeeson — APPROVED** [review]
LGTM

**Pull request closed without merging**
