### PR TITLE
filter, create file/folder, delete file/folder, rename file/folder in content browser

### PR DESCRIPTION
**Pull request by Minghui-Gao**

### CODE REVIEW

**Comment by Minghui-Gao** [comment]
image
image

**Comment by TejasJD** [comment]
What's the file button there for?

**Comment by TejasJD** [comment]
I'm expecting that, if you hover over the region which is not icon, the the option to create new file or folder pops up.

**Comment by BozhidarVelikov** [comment]
Isn't it going to be better to show the delete/rename popup on right-click over the file/folder?

**Review by LiamANeeson — DISMISSED** [review]

**Review by alex-mulkerrins — APPROVED** [review]

**Review by prajakta-kulkarni-git — APPROVED** [review]
Great work.

**Pull request merged**
