### PR TITLE
Adding documentation to the code base

### PR DESCRIPTION
**Pull request by alex-mulkerrins**
Added documentation to HorizonEngine :
- Utils
- scripting
- Renderer
- Logging
- Imgui
- File Management
- Events

### CODE REVIEW

**Comment by TejasJD** [comment]
Hi, I request a meeting after you pull recent changes from the main.

**Comment by prajakta-kulkarni-git** [comment]
Yeah, it would be better to do a meeting so that we can cleanly resolve these merge conflicts, let's make sure we get that done by tomorrow.

**Comment by prajakta-kulkarni-git** [comment]
Let's do a meeting tomorrow to resolve these merge conflicts cleanly.

**Comment by alex-mulkerrins** [comment]
Added more docs to the code base, we can do a meeting to go through conflicts

**Review by TejasJD — APPROVED** [review]
merge conflicts solved.

**Review by prajakta-kulkarni-git — APPROVED** [review]
Nice, documentation makes it easier to understand certain things, especially some of the rendering public API.

**Pull request merged**
