### PR TITLE
Active scene highlight 

### PR DESCRIPTION
**Pull request by BozhidarVelikov**

### CODE REVIEW

**Comment by TejasJD** [comment]
did you merge changes from main

**Comment by TejasJD** [comment]
This is how the maximized menu will look now (Upon merging #138).
image
And for the scenes panel, this is how it is:
image

**Comment by BozhidarVelikov** [comment]
Just tested with the new look. The icons are really nice

**Review by TejasJD — APPROVED** [review]
Nice work there with the Scenes Panel, this should make it easy to switch between scenes for now. In the future, when we make scenes more modular, we can do it in the way similar to unity, where we can load multiple scenes and show them in the hierarchy.

**Review by prajakta-kulkarni-git — APPROVED** [review]
Great work, switching between scenes is much faster now. Plus, the user can now see which scene is active.

**Pull request merged**
